### ISSUE TITLE
Upgrade Proffer to CakePHP 4

### ISSUE THREAD

**Issue by Schlaefer** [davidyell/CakePHP-Proffer#277]
I plan to upgrade a project using Proffer to CakePHP 4 over the coming weeks/months.

So maybe it would be a good idea to coordinate update efforts in advance to avoid duplicate work. If someone seriously starts to migrate the plugin they should probably announce it.

The repository is currently prefixed "CakePHP3", is it planned to have a new repository or is this one move on forward (CakePHP-core seems to prefer a "4.x"-branch approach for their plugins).

**Comment by davidyell** [comment]
If I get around to upgrading it, I'll probably rename the repo and add a branch, as I think it's neater. 

There is already an open pull request over at https://github.com/FriendsOfCake/cakephp-upload/pull/524 so that plugin may well beat me to it.

If you would like to start work on upgrading the plugin, I would be happy to review. I'll create a branch now.

**Comment by davidyell** [comment]
I have made a new `cake-4` branch and pushed some basic changes into it which cover updating the deprecated methods, fixing the tests, coding standards and a few other bits and bobs.

I will do some integration testing with a Cake 4 application when I get some more time.

**Comment by Schlaefer** [comment]
> There is already an open pull request over at FriendsOfCake/cakephp-upload so that plugin may well beat me to it.

It's fine, I'm not in a hurry. Since CakePHP 4 seems to be a rather painless update I don't want to switch plugins and rewrite without need. 

> If you would like to start work on upgrading the plugin, I would be happy to review. I'll create a branch now.

:+1: Thanks.

I just started the 3 to 4 migration by updating the composer file. I'm barely at step 2, so don't hold your breath right now. :wink:  Fixing the uploader is going to come up, but that might be next week or in six months, don't know yet.

**Comment by davidyell** [comment]
I will resolve this ticket now, as I have completed the basic upgrade, fixed the tests, cleaned up the code and implemented the new methods around the `UploadedFile` implementation.

If you have an application you're upgrading, or want to try it in a new CakePHP 4 application, please do so using the `cake-4` branch and feedback any issues you find.
