### ISSUE TITLE
Documentation examples improvements

### ISSUE THREAD

**Issue by hacheraw** [davidyell/CakePHP-Proffer#280]
Hello. First, I'd like to say that your documentation is one of the best and easiest documentation of a CakePHP Plugin I've ever seen.

----

I was facing a problem and took me a while until I realised that you use `photo` as table column on Behaviour and Built-in validation examples but you use `image` for the inputs and Basic Validation examples. I think they should all be the same (photo)

----

Also, it could be a good addition to mention that `bake` command adds basic validation like:

```php
$validator
    ->scalar('photo')
    ->maxLength('photo', 255)
    ->allowEmptyString('photo');
```

That validation takes place before the plugin logic so Cake throws this error to the user: "The provided value is invalid" since it is a file and not a string.

Other than that, I haven't faced any problem  following the documentation

**Comment by davidyell** [comment]
Thank you for your kind comments. I will get some documentation updates done
